# Generated by Django 4.1.6 on 2023-02-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='base/static/img/default/', null=True, upload_to='base/static/img/upload/'),
        ),
    ]
