# Generated by Django 4.1.6 on 2023-02-02 20:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='Pedido',
        ),
    ]
