# Generated by Django 4.1.6 on 2023-02-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_tarea_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.ImageField(blank=True, default='base/static/img/default/', null=True, upload_to='base/static/img/upload/')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='base.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='alergenos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='apto_para',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='base.servicio'),
        ),
    ]
