# Generated by Django 4.1.6 on 2023-02-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_servicio_pedido_productos_producto_alergenos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='servicios',
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, related_name='productos', to='base.producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='servicios',
            field=models.ManyToManyField(blank=True, null=True, related_name='servicios', to='base.servicio'),
        ),
    ]
