# Generated by Django 4.1.6 on 2023-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_pedido_productos_remove_pedido_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='base.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='servicios', to='base.servicio'),
        ),
    ]
