# Generated by Django 4.1.6 on 2023-02-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='Default', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='base/static/img/default/', null=True, upload_to='base/static/img/upload/'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, default='base/static/img/default/', null=True, upload_to='base/static/img/upload/'),
        ),
    ]
