# Generated by Django 4.1.6 on 2023-02-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_pedido_direccion_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
